//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace prjWebCsEntityFramOnlineExam
{
    using System;
    using System.Collections.Generic;
    
    public partial class Etudiant
    {
        public string EtudiantID { get; set; }
        public string Nom { get; set; }
        public string Mot2Passe { get; set; }
        public Nullable<double> Note { get; set; }
    }
}
