//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace prjWebCsEntityFramOnlineExam
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class teaccartOnlineSqlDBEntities : DbContext
    {
        public teaccartOnlineSqlDBEntities()
            : base("name=teaccartOnlineSqlDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Etudiant> Etudiants { get; set; }
        public virtual DbSet<Question> Questions { get; set; }
        public virtual DbSet<Repons> Reponses { get; set; }
    }
}
